### ISSUE TITLE
Can NPKit only trace workloads launched by MSCCL tests or more than that  

### ISSUE THREAD

**Issue by ZhiyiHu1999** [microsoft/NPKit#27]
I found in the example for MSCCL that the workload is launched by MSCCL tests, does that mean NPKit can only trace workloads generated by the MSCCL tests? Or NPKit can trace arbitrary workloads that involves GPU communications?

**Comment by yzygitzh** [comment]
Hi,
NPKit requires code modification in CCL library. Currently it’s officially supported by:
1) [Azure MSCCL](https://github.com/Azure/msccl). This is MSCCL for NVIDIA production maintained by Azure. It’s a superset of NCCL and will periodically sync up with latest NCCL.
2) [AMD RCCL](https://github.com/ROCm/rccl). This is AMD RCCL. Both NPKit and MSCCL are already merged to upstream.

**Comment by ZhiyiHu1999** [comment]
Well, thanks for the answer. But I think I mean a different thing. That is can we use NPKit to profile a real workload that is not generated by msccl-tests？

**Comment by yzygitzh** [comment]
Yes just make sure that workload uses the communication binary with NPKit modifications.

**Comment by ZhiyiHu1999** [comment]
OK， thanks！
